### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BwanaBob** [BwanaBob/opie#1]
- [ ] Data retention for working data (database)
- [ ] Data retention for options (file)
- [ ] Name change throttling
- [ ] Slash commands
- [ ] Multiple message "rules" per server with "actions" (delete, notify, timeout, etc.)
- [ ] Configurable options and rules
